# Generated by Django 2.1.7 on 2019-03-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_trampo_agil', '0002_auto_20190315_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidatos',
            new_name='Candidato',
        ),
    ]
