# Generated by Django 2.1.7 on 2019-03-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_trampo_agil', '0003_auto_20190315_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCandidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=2)),
                ('descrição', models.TextField(blank=True, max_length=240, null=True)),
            ],
        ),
    ]
