# Generated by Django 2.1.7 on 2019-03-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_trampo_agil', '0004_logincandidato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginCandidato',
            new_name='LoginCandidatos',
        ),
    ]
