# Generated by Django 2.1.7 on 2019-03-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_trampo_agil', '0005_auto_20190317_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logincandidatos',
            old_name='nome',
            new_name='senha',
        ),
        migrations.RemoveField(
            model_name='logincandidatos',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='logincandidatos',
            name='descrição',
        ),
    ]
