# Generated by Django 2.1.7 on 2019-03-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_trampo_agil', '0002_auto_20190315_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=1000)),
                ('salario', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_trampo_agil.Empresa')),
            ],
        ),
    ]
