# Generated by Django 2.1.7 on 2019-03-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_trampo_agil', '0003_auto_20190315_1458'),
        ('mural_vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vagas',
            new_name='Vaga',
        ),
    ]
